"""Generate 2d coordinates for visualizing a set of high-dimensional vectors. Generated by Codex"""

from typing import Protocol

import numpy as np
from paper_clustering.data_models import EmbeddedPaper


class UMAPReducer(Protocol):
    """A fitted UMAP reducer capable of projecting new vectors."""

    def transform(self, data: np.ndarray) -> np.ndarray: ...


def _as_matrix(data: list[np.ndarray] | list[EmbeddedPaper]) -> np.ndarray:
    """Extract area vectors from papers and validate a homogeneous vector matrix."""
    if not data:
        return np.empty((0, 0), dtype=float)

    vectors = [
        item.embeddings.area_vector if isinstance(item, EmbeddedPaper) else item
        for item in data
    ]
    matrix = np.asarray(vectors, dtype=float)
    if matrix.ndim != 2:
        raise ValueError("data must contain one-dimensional vectors of the same length")
    if not np.isfinite(matrix).all():
        raise ValueError("data vectors must contain only finite values")
    return matrix


def _coordinates(matrix: np.ndarray) -> list[tuple[float, float]]:
    """Convert a two-column coordinate array into the public return type."""
    return [tuple(map(float, point)) for point in matrix]


def generate_umap(
    data: list[np.ndarray] | list[EmbeddedPaper],
    reducer: UMAPReducer,
) -> list[tuple[float, float]]:
    """Project data into the coordinate space of a fitted UMAP ``reducer``."""
    matrix = _as_matrix(data)
    if len(matrix) == 0:
        return []
    return _coordinates(reducer.transform(matrix))


def generate_tsne(
    data: list[np.ndarray] | list[EmbeddedPaper],
) -> list[tuple[float, float]]:
    """Generate deterministic t-SNE coordinates from vectors or paper area embeddings."""
    matrix = _as_matrix(data)

    from sklearn.manifold import TSNE

    # t-SNE requires perplexity to be smaller than the number of samples.
    perplexity = min(30, max(1, (len(matrix) - 1) // 3))
    reducer = TSNE(
        n_components=2,
        perplexity=perplexity,
        init="random",
        random_state=42,
    )
    return _coordinates(reducer.fit_transform(matrix))
