"""This file loads the gemma-3 4b model and exposes an API which lets it generate weak labels from sentences. Code mostly generated by Gemini"""

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch
import os
from dotenv import load_dotenv
from huggingface_hub import login

load_dotenv()
hf_token = os.getenv("HF_TOKEN")
login(token=hf_token)
torch.cuda.empty_cache()

model_id = "google/gemma-3-4b-it"

# 1. Load the text-only tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)

# loading in 4bit precision because 8 bit precision is broken (causes infinite loop of error messages
# "MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization").
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    dtype=torch.bfloat16,
    device_map="cuda" if torch.cuda.is_available() else "mps",
    attn_implementation="sdpa",
)

# 3. Define your text chat messages
messages = [
    {
        "role": "user",
        "content": "What is the difference between semantic search and keyword search?",
    }
]

# 4. Format the conversation and move token IDs to the GPU
prompt = tokenizer.apply_chat_template(
    messages, add_generation_prompt=True, tokenize=False
)
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
print(inputs)

# 5. Generate the text response
with torch.no_grad():
    output_ids = model.generate(
        **inputs, max_new_tokens=512, do_sample=True, temperature=0.7, top_p=0.9
    )

# 6. Decode and isolate the new response text
generated_ids = output_ids[0, inputs.input_ids.shape[1] :]
response = tokenizer.decode(generated_ids, skip_special_tokens=True)
print(response)
