"""This file loads the gemma-3 1b model and exposes an API which lets it generate weak labels from sentences. Code mostly generated by Gemini"""

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch
import os
from dotenv import load_dotenv
from huggingface_hub import login
import time
import spacy
from math import ceil
from tqdm import tqdm
import logging

from .extract_intro import ArxivSection


class SLMWeakLabelGen:
    model_id: str
    tokenizer: AutoTokenizer
    bnb_config: BitsAndBytesConfig
    model: AutoModelForCausalLM
    parser: spacy.Language

    def __init__(self, load_4bit=True):
        load_dotenv()
        hf_token = os.getenv("HF_TOKEN")
        login(token=hf_token)
        torch.cuda.empty_cache()
        self.model_id = "google/gemma-3-4b-it"
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        # 8bits does not work on my computer. Causes an infinite loop and is probably a bug in bitsandbytes.
        self.bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.float16,
        )
        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_id,
            quantization_config=self.bnb_config if load_4bit else None,
            dtype=torch.bfloat16,
            device_map="cuda" if torch.cuda.is_available() else "mps",
            attn_implementation="sdpa",
        )
        self.parser = spacy.load("en_core_web_sm")

    def _structure_message(section, prev, target, next):
        return [
            {
                "role": "system",
                "content": "You are an expert mathematician strictly reviewing academic papers.",
            },
            {
                "role": "user",
                "content": "Determine if the target sentence contains information about a specific proof technique used by the authors. Respond ONLY with an integer from 0-100, where 0 indicates no useful information and 100 indicates mention of an essential proof technique or the main proof idea. Do not give points to sentences describing prior work."
                f"Section: {section}\n {prev} <TARGET> {target} <TARGET/> {next}",
            },
        ]

    def _format_message_batch(self, sections, prevs, targets, nexts):
        msgs = [
            SLMWeakLabelGen._structure_message(s, p, t, n)
            for s, p, t, n in zip(sections, prevs, targets, nexts)
        ]
        msgs = [
            self.tokenizer.apply_chat_template(
                msg, tokenize=False, add_generation_prompt=True
            )
            for msg in msgs
        ]
        return self.tokenizer(
            msgs,
            return_tensors="pt",
            padding=True,
            add_special_tokens=False,  # Avoids double <bos> tokens
        ).to("cuda")

    def _format_messages(self, sections, prevs, targets, nexts, batch_size=8):
        n = len(targets)
        for i in range(ceil(n / batch_size)):
            yield self._format_message_batch(
                sections[batch_size * i : batch_size * (i + 1)],
                prevs[batch_size * i : batch_size * (i + 1)],
                targets[batch_size * i : batch_size * (i + 1)],
                nexts[batch_size * i : batch_size * (i + 1)],
            )

    def label_paper(self, sections: list[ArxivSection], batch_size=8):
        """Generates weak labels for each sentence in the provided text using the model.

        Parameters:
        sections: list[ArxivSection]
            Ordered sections and their arXiv metadata.

        Returns:
        list[int]
            A weak label between 0-100 rating the importance of each sentence in the
            text, in terms of how much information it carries about the techniques used
            in the paper.
        """
        # For each sentence, record its section, the previous sentence, and the following sentence.
        secs, prevs, targets, nexts = [], [], [], []
        for section in sections:
            sentences = list(self.parser(section.text).sents)
            for sentence_index, sent in enumerate(sentences):
                secs.append(section.section_header)
                prevs.append(sentences[sentence_index - 1] if sentence_index else "")
                nexts.append(
                    sentences[sentence_index + 1]
                    if sentence_index + 1 < len(sentences)
                    else ""
                )
                targets.append(sent)

        results = []

        batches = self._format_messages(secs, prevs, targets, nexts, batch_size)
        with torch.no_grad():
            for batch in tqdm(batches):
                start = time.perf_counter()
                output_ids = self.model.generate(
                    **batch,
                    max_new_tokens=150,
                    do_sample=False,
                    pad_token_id=self.tokenizer.pad_token_id,
                )
                end = time.perf_counter()
                logging.debug(
                    f"Batch of size {batch_size} took {end-start} seconds to label.\n"
                )
                input_lengths = batch.input_ids.shape[1]
                generated_tokens = output_ids[:, input_lengths:]
                results.extend(
                    self.tokenizer.batch_decode(
                        generated_tokens, skip_special_tokens=True
                    )
                )
        return results


if __name__ == "__main__":
    from .extract_intro import get_sections
    import requests, spacy

    parser = spacy.load("en_core_web_sm")
    with requests.session() as session:
        paper = get_sections(session, "2404.05864")
        paper = [
            section for section in paper if section.section_header == "Introduction"
        ]

    print(len(paper))
    label_gen = SLMWeakLabelGen()
    labels = label_gen.label_paper(paper)
    print(labels)

    i = 0
    for section in paper:
        for sent in parser(section.text).sents:
            print(sent.text, labels[i])
            i += 1
